version: '3.7'

services:

  nginx:
    image: nginx:1.11.10-alpine
    container_name: nginx-container
    ports:
      - 8000:80
    depends_on:
      - app
    networks:
      - webnet
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/app

  app:
    build: .
    depends_on:
      - db
    networks:
      - webnet
      - dbnet
    volumes:
      - product-img-data:/app/product-images
      - profile-img-data:/app/profile-uploads

  db:
    image: mysql:5.7
    container_name: db-container
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - dbnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    networks:
      - dbnet

volumes:
  db-data:
  product-img-data:
  profile-img-data:

networks:
  dbnet:
    driver: bridge
  webnet:
    driver: bridge

